### ISSUE TITLE
Markdown notes for each task

### ISSUE THREAD

**Issue by haitianxu2024** [Team-07-CSE-210-FA-24/cse210-fa24-group07#32]
Create Markdown notes for each task in the project

- [x] Add note saying that markdown is supported @haitianxu2024 
- [x] Debug note not fetched issue @ishanppendse 
- [x] Render to do lists @byunsy 
- [x] External library @ishanppendse 
- [x] We need to clean current code up so that we adopt a single approach about external library

**Comment by haitianxu2024** [comment]
I have transferred the library Markdown to the integrated on in the edit part, the MD finally appeared

**Comment by ishanppendse** [comment]
Fixed in #62 #40 #35
